services:
  runner:
    build:
      context: .
      network: host
    image: github-runner
    init: true
    env_file:
      - path: .env
        required: true
    environment:
      RUNNER_NAME: ${RUNNER_NAME:-docker-runner}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,linux,x64}
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins:/usr/local/lib/docker/cli-plugins
      - /actions-runner/_work:/actions-runner/_work
    group_add:
        - "989"
